import { GetServerSideProps } from "next";
import Head from "next/head";
import { createContext, useState } from "react";

import { withServerSideProps } from "hoc/withServerSideProps";
import HomePage from "@components/pages/Home";
import { positionService } from "services/position";
import { candidateService } from "services/candidate";
import AppModal from "@components/AppModal";

export const PositionsContext = createContext({});

const submitApplyForm = async (data: any) => {
  await candidateService.postApplyForm(data);
};

export default function Home({ allPositions }: any) {
  const [visibleModal, setVisibleModal] = useState(false);

  const handleToggleModal = () => {
    setVisibleModal(!visibleModal);
  };

  return (
    <PositionsContext.Provider
      value={{ allPositions, submitApplyForm, handleToggleModal }}
    >
      <div className="homepage">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HomePage />
        <AppModal
          title="Example modal"
          open={visibleModal}
          onCancel={handleToggleModal}
          onOk={handleToggleModal}
        >
          <h1>Bạn đã gửi thông tin thành công!</h1>
        </AppModal>
      </div>
    </PositionsContext.Provider>
  );
}

export const getServerSideProps: GetServerSideProps = withServerSideProps(
  async () => {
    const result = await positionService.getAllPositions();
    const allPositions = result?.allPositions.map((item: any) => ({
      label: item?.name,
      value: item?.id,
      key: item?.id,
      description: item?.description,
    }));
    return { allPositions };
  }
);
