import { GetServerSideProps } from "next";
import Head from "next/head";

import { withServerSideProps } from "hoc/withServerSideProps";
import HomePage from "@components/pages/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = withServerSideProps(
  (ctx: any) => ctx
);
